batch_size: 64
dataset: ''
exclude_bn_bias: false
feat_dim: 128
final_lr: 0.0
first_conv: true
gpus: 1
hidden_mlp: 4608
learning_rate: 0.001
max_epochs: 26
maxpool1: true
num_nodes: 1
num_samples: 209130
optimizer: adam
start_lr: 0.0
temperature: 0.1
warmup_epochs: 3
weight_decay: 1.0e-06
